name: aurum
description: A support package that makes Golden Tests easier.
version: 0.0.1
homepage: https://github.com/FBisca/aurum

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
