name: aurum
description: A support package that makes Golden Tests easier.
version: 0.0.1
homepage: https://github.com/FBisca/aurum

environment:
  sdk: '>=2.18.5 <3.7.4'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.8.0
  equatable: 2.0.5

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: packages/aurum/fonts/Roboto-Regular.ttf
